Party/Models/ErrorViewModel.cs
namespace Party.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Party/Models/GuestResponse.cs
using System.ComponentModel.DataAnnotations;


namespace Party.Models
{
	public class GuestResponse
	{
		[Key]
		public int Id { get; set; }

		[Required(ErrorMessage = "Lütfen isminizi giriniz !")]
		public string Name { get; set; }

		[Required(ErrorMessage = "Lütfen mail adresinizi giriniz !")]
		[EmailAddress]
		public string Email { get; set; }


		[Required(ErrorMessage = "Lütfen telefon numaranızı giriniz !")]
		public string Phone { get; set; }

		[Required(ErrorMessage = "Katılım bilgisini doldurunuz !")]
		public bool? WillAttend { get; set; }
	}
}

Party/Controllers/GuestController.cs
using Party.Data;
using Party.Models;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace Party.Controllers
{
	public class GuestController : Controller
	{



		private readonly ApplicationDbContext _db;

		public GuestController(ApplicationDbContext db)
		{
			_db = db;
		}


		[HttpGet]
		public IActionResult Index()
		{
			return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Index(GuestResponse obj)
		{
			if (ModelState.IsValid)
			{
				_db.guestResponses.Add(obj);
				_db.SaveChanges();
				return View("Thanks", obj);
			}
			else
			{
				return View();
			}
		}

		[HttpGet]
		public IActionResult List()
		{

			var result = from guest in _db.guestResponses
						 where guest.WillAttend == true
						 select new GuestResponse
						 {
							 Id = guest.Id,
							 Email = guest.Email,
							 Name = guest.Name,
							 Phone = guest.Phone,
							 WillAttend = guest.WillAttend
						 };

			IEnumerable<GuestResponse> objGuestList = result.ToList();



			return View(objGuestList);
		}

		[HttpGet]
		public IActionResult Thanks()
		{
			return View();
		}

	}
}

Party/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Party.Models;
using System.Diagnostics;

namespace Party.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Party/Views/Guest/Index.cshtml
@model Party.Models.GuestResponse

@{
    ViewData["Title"] = "Başvuru";
}

<section>
    <h3 class="text-center m-2 p-2">KATILIM BILGILERI</h3>
    <partial name="_Form" />

</section>

Party/Views/Guest/List.cshtml
@model IEnumerable<Party.Models.GuestResponse>

@{
    ViewData["Title"] = "Yarışmacı Listesi";
}

<section>
    <div class="text-center p-2">
        <h2>Yarışmaya katılacakların listesi</h2>
        <table class="table table-bordered table-striped table-sm">
            <thead>
                <tr><th>Name</th><th>Email</th><th>Phone</th></tr>
            </thead>
            <tbody>
                @foreach (Party.Models.GuestResponse r in Model)
                {
                    <tr>
                        <td>@r.Name</td>
                        <td>@r.Email</td>
                        <td>@r.Phone</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</section>

Party/Views/Guest/ListGuest.cshtml
@model IEnumerable<Party.Models.GuestResponse>

@{
    ViewData["Title"] = "Guest List";
}

<section>
    <div class="text-center p-2">
        <h2>Here is the list of people attending the party</h2>
        <table class="table table-bordered table-striped table-sm">
            <thead>
                <tr><th>Name</th><th>Email</th><th>Phone</th></tr>
            </thead>
            <tbody>
                @foreach (Party.Models.GuestResponse r in Model)
                {
                    <tr>
                        <td>@r.Name</td>
                        <td>@r.Email</td>
                        <td>@r.Phone</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</section>

Party/Views/Guest/Thanks.cshtml
@model Party.Models.GuestResponse
@{
    ViewData["Title"] = "Thanks";
}

<section>
    <div>
        <h1>Teşekkürler, @Model.Name!</h1>
        @if (Model.WillAttend == true)
        {
            @:Katılıcağını görmek çok güzel. Katılmanı dört gözle bekliyoruz
        }
        else
        {
            @:Gelemeyeceğin için üzüldüm, fakat haber verdiğin için teşekkürler.
        }
    </div>
    Katılımcı listesini görmek için <a asp-controller="Guest" asp-action="List" style="color:#FF0000">tıklayınız.</a>
</section>

Party/Views/Guest/_Form.cshtml
@model Party.Models.GuestResponse

<form method="post" class="m-2">
    <div asp-validation-summary="All"></div>

    <!-- Name input -->
    <div class="form-outline">
        <label asp-for="Name" class="form-label" for="name">Adınız:</label>
        <input asp-for="Name" type="text" id="name" class="form-control" />
    </div>

    <!-- Email input -->
    <div class="form-outline mb-4">
        <label asp-for="Email" class="form-label" for="email">Mail Adresiniz:</label>
        <input asp-for="Email" type="email" id="email" class="form-control" />
    </div>

    <!-- Phone input -->
    <div class="form-outline mb-4">
        <label asp-for="Phone" class="form-label" for="number">Telefon Numaranız:</label>
        <input asp-for="Phone" type="number" id="number" class="form-control" />
    </div>
    <div class="form-outline mb-4">
        <label>Katılıcak mısınız ?</label>
        <select asp-for="WillAttend" class="form-control">
            <option value="">Seçiniz.</option>
            <option value="true">Evet katılacağım.</option>
            <option value="false">Katılamıcağım.</option>
        </select>
    </div>

    <!-- Submit button -->
    <button type="submit" class="btn btn-dark btn-block mb-4">
        Formu Gönder
    </button>
</form>

Party/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Ana Sayfa";
}

<section>
    <partial name="_Info" />
</section>

Party/Views/Home/_Info.cshtml
<div class="container" style="margin-top:50px;">
    <div class="row">

        <div class="col-md-2">
            <partial name="_Sidebar" />
        </div>
        <div class="col-md-10" style="font-size: 20px">
            <h3>Yarışma Hakkında</h3>
            <img src="~/images/info.jpeg" class="rounded float-start" style="height:300px"/>
            <p style="text-align: justify">
                Türkiye dünya çapında olağanüstü bir yarışmaya ev sahipliği yapıyor.
                Teknofest etkinliğinin bir parçası olarak, Dijital Dönüşüm Ofisi Hack
                İstanbul 2021 Yarışmasını düzenliyor.
            </p>
            <p style="text-align: justify">
                Hackerların becerileri, dünyanın önde gelen uzmanlarının rehberliğinde
                hazırlanan gelişmiş gerçek yaşam siber saldırı senaryoları ile sınırlara
                itilecektir. Yarışmaya kayıt için son tarih 30 Haziran.
            </p>
            <p style="text-align: justify">
                Ön seçim aşamasında başarılı olan hackerlar, farklı zorluk ve karmaşıklık
                seviyelerine sahip zorlukları içeren jeopardy tarzı bir CTF olan 2.ön seçim
                mücadelesine hak kazanacaklar. 18 saatlik CTF mücadelesi sadece en iyi bilgisayar
                korsanlarını final turuna taşıyacak. CTF'Yİ başaran ilk 10 takım, 21-26 Eylül tarihlerinde
                İstanbul Atatürk Havalimanı'nda düzenlenecek olan büyük final etabı için İstanbul'a davet edilecek.
            </p>

            <p style="text-align: justify">
                Yarışma için uygun Katılımcı Eğitim seviyeleri
                <br />
                - Lise Öğrencileri<br />
                - Ön Lisans Öğrencileri, Lisans Öğrencileri, Yüksek Lisans Öğrencileri ve Doktora Öğrencileri <br />
                - Üniversite Mezunu
            </p>


            <a asp-controller="Guest" asp-action="Index" class="btn btn-dark btn-lg btn-block">Başvuru yapmak için Tıklayınız !</a>
        </div>

    </div>
</div>

Party/Views/Home/_PartyInfo.cshtml
<div class="container" style="margin-top:50px;">
    <div class="row">

        <div class="col-md-2">
            <partial name="_Sidebar" />
        </div>
        <div class="col-md-10" style="font-size: 20px">
            <h3>Yarışma Hakkında</h3>
            <p style="text-align: justify">
                Türkiye dünya çapında olağanüstü bir yarışmaya ev sahipliği yapıyor.
                Teknofest etkinliğinin bir parçası olarak, Dijital Dönüşüm Ofisi Hack
                İstanbul 2021 Yarışmasını düzenliyor.
            </p>
            <p style="text-align: justify">
                Hackerların becerileri, dünyanın önde gelen uzmanlarının rehberliğinde
                hazırlanan gelişmiş gerçek yaşam siber saldırı senaryoları ile sınırlara
                itilecektir. Yarışmaya kayıt için son tarih 30 Haziran.
            </p>
            <p style="text-align: justify">
                Ön seçim aşamasında başarılı olan hackerlar, farklı zorluk ve karmaşıklık
                seviyelerine sahip zorlukları içeren jeopardy tarzı bir CTF olan 2.ön seçim
                mücadelesine hak kazanacaklar. 18 saatlik CTF mücadelesi sadece en iyi bilgisayar
                korsanlarını final turuna taşıyacak. CTF'Yİ başaran ilk 10 takım, 21-26 Eylül tarihlerinde
                İstanbul Atatürk Havalimanı'nda düzenlenecek olan büyük final etabı için İstanbul'a davet edilecek.
            </p>

            <p style="text-align: justify">
                Yarışma için uygun Katılımcı Eğitim seviyeleri
                <br />
                - Lise Öğrencileri<br />
                - Ön Lisans Öğrencileri, Lisans Öğrencileri, Yüksek Lisans Öğrencileri ve Doktora Öğrencileri <br />
                - Üniversite Mezunu
            </p>


            <a asp-controller="Guest" asp-action="Index" class="btn btn-primary btn-lg btn-block">Başvuru yapmak için Tıklayınız !</a>
        </div>

    </div>
</div>

Party/Views/Home/_Sidebar.cshtml
<div
	class="nav flex-column nav-pills"
	role="tablist"
	aria-orientation="vertical"
>
	<a
		class="nav-link active"
		data-toggle="pill"
		href="/"
		role="tab"
		aria-controls="v-pills-hakkinda"
		aria-selected="true"
		>Yarışma Hakkında</a
	>
	<a
		class="nav-link"
		data-toggle="pill"
		href="/"
		role="tab"
		aria-controls="v-pills-sartname"
		aria-selected="false"
		>Yarışma Şartnamesi</a
	>
	<a
		class="nav-link"
		data-toggle="pill"
		href="/"
		role="tab"
		aria-controls="v-pills-takvim"
		aria-selected="false"
		>Yarışma Takvimi</a
	>
	<a
		class="nav-link"
		data-toggle="pill"
		href="/"
		role="tab"
		aria-controls="v-pills-video"
		aria-selected="false"
	>
		Yarışma Videoları</a
	>
	<a
		class="nav-link"
		data-toggle="pill"
		href="/"
		role="tab"
		aria-controls="v-pills-sorular"
		aria-selected="false"
		>Sık Sorulan Sorular</a
	>
	<a
		class="nav-link"
		data-toggle="pill"
		href="/"
		role="tab"
		aria-controls="v-pills-rapor"
		aria-selected="false"
		>Rapor Şablonları</a
	>

	<a
		class="nav-link"
		data-toggle="pill"
		href="/"
		role="tab"
		aria-controls="v-pills-finalist"
		aria-selected="false"
		>Finalist Takımlar</a
	>

	<a
		class="nav-link"
		data-toggle="pill"
		href="/"
		role="tab"
		aria-controls="v-pills-dereceler"
		aria-selected="false"
		>Dereceler</a
	>

	<a
		class="nav-link"
		href="/"
		role="tab"
		aria-controls="v-pills-oduller"
		aria-selected="false"
		>Ödüller</a
	>
	<a
		class="nav-link"
		data-toggle="pill"
		href="/"
		role="tab"
		aria-controls="v-pills-galeri"
		aria-selected="false"
		>Galeri</a
	>

	<a
		class="nav-link"
		data-toggle="pill"
		href="/"
		role="tab"
		aria-controls="v-pills-destekler"
		aria-selected="false"
		>Destekler</a
	>

	<a
		class="nav-link"
		data-toggle="pill"
		href="/"
		role="tab"
		aria-controls="v-pills-adres"
		aria-selected="false"
		>Yarışma Yeri Ve Tarihi</a
	>
</div>

Party/Views/Shared/_Footer.cshtml
<footer class="text-center text-white fixed-bottom" style="background-color: #3E3F3A;">
    <div class="container p-4"></div>
    <div class="text-center p-3" style="background-color: #3E3F3A;">
        &copy; 2021 - Hack İstanbul - <a asp-controller="Home" asp-action="Privacy" style="color:#FF0000">Gizlilik</a>
    </div>
</footer>

Party/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Hack Istanbul - @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/css/bootstrap.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Party.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <partial name="_Navbar" />
    </header>


    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <partial name="_Footer" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Party/Views/Shared/_Navbar.cshtml
<nav class="navbar navbar-dark navbar-expand-lg bg-primary">
    <div class="container-fluid">
        <a class="navbar-brand" asp-controller="Home" asp-action="Index">
            <img src="~/images/logo.png"
                 class="me-2"
                 height="20"
                 alt=""
                 loading="lazy" />
            <small>Hack İstanbul</small>
        </a>
    </div>
</nav>